### ISSUE TITLE
figure_source leads to error in host

### ISSUE THREAD

**Issue by bsherin** [bsherin/tactic#1023]
the root of the problem is that the host container doesn't have use_wait_tasks=True

So the question is: do I still use figure_source for anything

- Answer: It is only used in new projects when use_svg is not true. But currently use_svg will always be true

In one way or another this should be cleared up under the hood

```jsx
[2021-04-15 21:29:42,334] ERROR in app: Exception on /figure_source/4e6133fa-125e-43d8-b5ed-9e0044a8c732/ed18000c-c3f7-4d36-8151-bd4d0299dd5d [GET]

Traceback (most recent call last):

File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app

response = self.full_dispatch_request()

File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request

rv = self.handle_user_exception(e)

File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception

reraise(exc_type, exc_value, tb)

File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise

raise value

File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request

rv = self.dispatch_request()

File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request

return self.view_functions[rule.endpoint](**req.view_args)

File "/usr/local/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view

return func(*args, **kwargs)

File "/code/main_views.py", line 133, in figure_source

encoded_img = tactic_app.host_worker.post_and_wait(tile_id, "get_image", {"figure_name": figure_name})["img"]

File "/code/qworker.py", line 211, in post_and_wait

"reply_to": self.wait_worker.my_id,

AttributeError: 'HostWorker' object has no attribute 'wait_worker'
```

**Comment by bsherin** [comment]
I haven't seen this in a very long time.
