### ISSUE TITLE
Error messages aren't always displayed

### ISSUE THREAD

**Issue by AkivaSherin** [bsherin/tactic#1028]
here is an example of an error message that wasn't displayed (using a tile in a collection):

got option {'name': 'normalized_columns', 'type': 'pipe_select'}
got option {'name': 'classification_column', 'type': 'column_select'}
got option {'name': 'classifier_type', 'type': 'custom_list', 'special_list': ['naive_bayes', 'decision_tree']}
got option {'name': 'stoplist', 'type': 'list_select'}
got option {'name': 'normalizer_tile', 'type': 'tile_select'}
Aug 02, 2021, 23:11:00: in handle_delivery with task_type TileSizeChange
Aug 02, 2021, 23:11:06: in handle_delivery with task_type UpdateOptions
Aug 02, 2021, 23:11:06: in handle_delivery with task_type StartSpinner
Aug 02, 2021, 23:11:06: in handle_delivery with task_type RefreshTile
got RefreshTile
Aug 02, 2021, 23:11:06: <pre>An exception of type KeyError occured. Arguments:
('encoded_val',)
Traceback (most recent call last):
  File "/code/tile_base.py", line 620, in _do_the_refresh
    new_html = self.render_content()
  File "<string>", line 34, in render_content
  File "/code/remote_tile_object.py", line 97, in __getitem__
    return self._tbinstance.get_pipe_value(self.name, attr)
  File "/code/other_api_mixin.py", line 91, in get_pipe_value
    encoded_val = result["encoded_val"]
KeyError: 'encoded_val'

**Comment by AkivaSherin** [comment]
heres another:

Aug 02, 2021, 23:37:54: in handle_delivery with task_type load_source_and_instantiate
entering instantiate_tile_class
entering fully initialize
got doc type table
got option {'name': 'classification_column', 'type': 'column_select'}
got option {'name': 'classifier_type', 'type': 'custom_list', 'special_list': ['naive_bayes', 'decision_tree']}
got option {'name': 'stoplist', 'type': 'list_select'}
got option {'name': 'normalized_columns', 'type': 'pipe_select'}
Aug 02, 2021, 23:37:54: in handle_delivery with task_type TileSizeChange
Aug 02, 2021, 23:38:09: in handle_delivery with task_type UpdateOptions
Aug 02, 2021, 23:38:09: in handle_delivery with task_type StartSpinner
Aug 02, 2021, 23:38:09: in handle_delivery with task_type RefreshTile
got RefreshTile
Aug 02, 2021, 23:38:09: <pre>An exception of type NameError occured. Arguments:
("name 'normalized_data_list' is not defined",)
Traceback (most recent call last):
  File "/code/tile_base.py", line 620, in _do_the_refresh
    new_html = self.render_content()
  File "<string>", line 31, in render_content
NameError: name 'normalized_data_list' is not defined
</pre>
Aug 02, 2021, 23:38:09: in handle_delivery with task_type StopSpinner

**Comment by AkivaSherin** [comment]
and another:

Aug 02, 2021, 23:40:08: <pre>An exception of type NameError occured. Arguments:
("name 'normalization_tile' is not defined",)
Traceback (most recent call last):
  File "/code/tile_base.py", line 620, in _do_the_refresh
    new_html = self.render_content()
  File "<string>", line 59, in render_content
NameError: name 'normalization_tile' is not defined
</pre>
Aug 02, 2021, 23:40:08: in handle_delivery with task_type StopSpinner

**Comment by AkivaSherin** [comment]
I have a random theory that it could have to do with pre tags or something. I don't totally know what pre tags do but you can keep it in mind.

**Comment by bsherin** [comment]
Here is another

```
An exception of type TypeError occured. Arguments:
("'NoneType' object is not subscriptable",)
Traceback (most recent call last):
  File "/code/pseudo_tile_base.py", line 400, in exec_thread
    eval_res = eval(code_to_eval, globals(), globals())
  File "", line 1, in 
  File "/code/document_object.py", line 1093, in add_to_library
    _tworker.tile_instance.create_collection(collection_name, full_collection, self._doc_type, metadata_dict)
  File "/code/library_access_mixin.py", line 92, in create_collection
    if not result["success"]:
TypeError: 'NoneType' object is not subscriptable
```
