### ISSUE TITLE
Projects older than ~2017 generate server errors and don’t load

### ISSUE THREAD

**Issue by bsherin** [bsherin/tactic#1108]
```bash
posting register_container to the host with id b08739a1-d5be-41f3-931a-6c683fd5dcf0

[2022-06-20 15:10:26,625] ERROR in app: Exception on /main_project_in_context [POST]

Traceback (most recent call last):

  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app

    response = self.full_dispatch_request()

  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request

    rv = self.handle_user_exception(e)

  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request

    rv = self.dispatch_request()

  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request

    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)

  File "/usr/local/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view

    return func(*args, **kwargs)

  File "/code/project_manager.py", line 164, in main_project_in_context

    full_collection_name = mdata["collection_name"]
```

This is what an old project entry looks like:

1. **_id**:
    
    58bf3df612df890001823a26
    
2. **project_name**:
    
    "starting_with_combined_posts"
    
3. **file_id**:
    
    58bf67beed18be0001d48340
    
4. **metadata**:
    
    Object
    
    1. **updated**:
        
        2017-03-07 20:09:01.774
        
    2. **datetime**:
        
        2017-03-07 17:10:45.850
        
    3. **notes**:
        
        "Fiddling with the format of dates in the combined dataset."
        
    4. **tags**:
        
        "drk12 drk12/combined drk12/cleaning"
        

This is a new one

1. **_id**:
    
    62acd6c0ddbfe50840dadd56
    
2. **metadata**:
    
    Object
    
    1. **datetime**:
        
        2022-06-17 14:32:16.081
        
    2. **updated**:
        
        2022-06-18 14:05:38.041
        
    3. **tags**:
        
        "fcp/analysis"
        
    4. **notes**:
        
        "Here I am using the new tiles to cluster fcp responses. It includes us..."
        
    5. **type**:
        
        "table"
        
    6. **collection_name**:
        
        "bsherinrem.data_collection.fcp_edited_nononetext"
        
    7. **loaded_tiles**:
        
        Array
        
    8. **save_style**:
        
        "b64save_react"
        
3. **project_name**:
    
    "fcp_clustering"
    
4. **file_id**:
    
    62ae2202f61324984e36ec46

**Comment by bsherin** [comment]
full_collection_name isn't used. And I think short_collection_name is only used for display on the header of the main table. So I can just pass a random string.
