### ISSUE TITLE
Can't create new collections from code

### ISSUE THREAD

**Issue by bsherin** [bsherin/tactic#1200]
This creates the collection but generates an error:

`self.create_collection("discussions3", {"test": [{"name": "hello", "val": 2}, {"name": "blah", "val": 3}]})`

```
An exception of type Exception occured. Arguments:
('Error submitting response for task type create_collection for my_id a488ee76-dbe1-4a49-8df8-de673ace9fbe
\nAn exception of type TypeError occurred. Arguments:\n(\'Object of type datetime is not JSON serializable\',)\nTraceback (most recent call last):\n  File "/code/qworker.py", line 317, in handle_event\n    self.submit_response(task_packet)\n  File "/code/qworker.py", line 265, in submit_response\n    self.post_packet(reply_to, task_packet, callback_id=task_packet["callback_id"])\n  File "/code/qworker.py", line 171, in post_packet\n    body=json.dumps(task_packet))\n         ^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/local/lib/python3.11/json/__init__.py", line 231, in dumps\n    return _default_encoder.encode(obj)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/local/lib/python3.11/json/encoder.py", line 200, in encode\n    chunks = self.iterencode(o, _one_shot=True)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/local/lib/python3.11/json/encoder.py", line 258, in iterencode\n    return _iterencode(o, 0)\n           ^^^^^^^^^^^^^^^^^\n  File "/usr/local/lib/python3.11/json/encoder.py", line 180, in default\n    raise TypeError(f\'Object of type {o.__class__.__name__} \'\nTypeError: Object of type datetime is not JSON serializable\n
',)
Traceback (most recent call last):
  File "/code/pseudo_tile_base.py", line 432, in exec_thread
    eval_res = eval(code_to_eval, globals(), globals())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "", line 1, in 
  File "/code/library_access_mixin.py", line 150, in create_collection
    raise Exception(result["message"])
Exception: Error submitting response for task type create_collection for my_id a488ee76-dbe1-4a49-8df8-de673ace9fbe
An exception of type TypeError occurred. Arguments:
('Object of type datetime is not JSON serializable',)
Traceback (most recent call last):
  File "/code/qworker.py", line 317, in handle_event
    self.submit_response(task_packet)
  File "/code/qworker.py", line 265, in submit_response
    self.post_packet(reply_to, task_packet, callback_id=task_packet["callback_id"])
  File "/code/qworker.py", line 171, in post_packet
    body=json.dumps(task_packet))
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type datetime is not JSON serializable
```

**Comment by bsherin** [comment]
Fixed
