### ISSUE TITLE
problem loading old project saves

### ISSUE THREAD

**Issue by bsherin** [bsherin/tactic#860]
these don't load: activity_info_editing, CVA_for_drk12
activity_info_editing was last modified feb 22, 2017

work_on_cohort_info has this error on local

> got the project_dict
> looping over project_dict items
> error with attr doc_dict: KeyError metadata
> looping over tile_instances

in docInfo.recreate_from_save it expects a key "metadata"
I assume that didn't used to be there.

**Comment by bsherin** [comment]
I fixed the above problem and another
Now I can't open projects older than May 6 2016

<pre>Error loading project dict</pre><pre>
An exception of type error occurred. Arguments:
('Error -3 while decompressing data: incorrect header check',)
Traceback (most recent call last):
  File "/code/main.py", line 260, in recreate_from_save
    project_dict = read_project_dict(self.fs, self.mdata, save_dict["file_id"])
  File "/code/communication_utils.py", line 89, in read_project_dict
    project_dict = pickle.loads(zlib.decompress(fs.get(file_id).read()).decode("utf-8", "ignore").encode("ascii"))
zlib.error: Error -3 while decompressing data: incorrect header check
</pre>

**Comment by bsherin** [comment]
It seems like no projects this old still exist on the server. So this can be closed
